apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::957007403992:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::957007403992:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K7MJZDR9HZTR
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-21T11:47:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1242"
  uid: 25721ea5-2549-4afe-9cb6-383db5a30650